language: objective-c
git:
  depth: 10
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2
before_install:
    - rvm use system
    - sudo gem install activesupport --version 4.2.5
    - sudo gem install cocoapods --no-prerelease --no-rdoc --no-ri --no-document
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD
    - cd TMLKit && pod install && cd ..
    - cd TMLSandbox && pod install && cd ..
    - cd Demo && pod install && cd ..
    - cd $TRAVIS_BUILD_DIR
#script: 
    - xctool -workspace TMLKit/TMLKit.xcworkspace -configuration Release -scheme TMLKit CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build -sdk $TRAVIS_XCODE_SDK 
    - xctool -workspace TMLKit/TMLKit.xcworkspace -configuration Release -scheme TMLKit CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test -test-sdk $TRAVIS_XCODE_SDK -parallelize
    - xctool -workspace Demo/Demo.xcworkspace -configuration Release -scheme Demo CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build -sdk $TRAVIS_XCODE_SDK 
    - xctool -workspace TMLSandbox/TMLSandbox.xcworkspace -configuration Release -scheme TMLSandbox CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build -sdk $TRAVIS_XCODE_SDK 
#    - rake test
